version: '2'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: 77M
        reservations:
          cpus: '0.01'
          memory: 30M

  hh-blog:
    image: hahyunkim/hxhkim.github.io:1.4.0
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=hhblog.com
      - VIRTUAL_PORT=80
    deploy:
      mode: replicated
      replicas: 2 # https://docs.docker.com/compose/compose-file/deploy/#replicas
      resources:  # https://docs.docker.com/compose/compose-file/compose-file-v3/#resources
        limits:
          cpus: '0.05'
          memory: 20M
        reservations:
          cpus: '0.01'
          memory: 6M
    
  ig-blog:
    image: aaingyunii/aaingyunii.github.io:latest
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=igblog.com
      - VIRTUAL_PORT=80
  
  js-blog:
    image: juseonlee/assomdevgit.github.io:1.4.0
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=jsblog.com
      - VIRTUAL_PORT=80
  
  jh-blog:
    image: mato94/shims94.github.io:1.4.0
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=jhblog.com
      - VIRTUAL_PORT=80
