# fly.toml app configuration file generated for hahyun-blog on 2023-10-23T10:47:00+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "hahyun-blog"
primary_region = "nrt"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
