name: Fly Deploy
on:
  push:
    branches:
      - main
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
      name: Deploy app
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3 # checkout repository
        - uses: superfly/flyctl-actions/setup-flyctl@main # use flyio
        - run: flyctl deploy
