name: Fly Deploy
on:
  push:
    branches:
      - main
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
      name: Deploy app
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4 # checkout repository
        - uses: superfly/flyctl-actions/setup-flyctl@master # use flyio https://github.com/superfly/flyctl-actions/tree/master
        - run: flyctl deploy
